// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa3ww_GZH7SabiN1nszzYtmwjEtwcCp0c',
    appId: '1:361313252323:web:ee6948b45af5f787a966d6',
    messagingSenderId: '361313252323',
    projectId: 'event-c5221',
    authDomain: 'event-c5221.firebaseapp.com',
    storageBucket: 'event-c5221.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaxBGaytK429cn9X98lD9wwRDu-w7TDhM',
    appId: '1:361313252323:android:2eeac0f8e4d29c55a966d6',
    messagingSenderId: '361313252323',
    projectId: 'event-c5221',
    storageBucket: 'event-c5221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj9_KNHx3GFoV2cekrmX6m4T2RFyWxBC0',
    appId: '1:361313252323:ios:92898f0ef7968aada966d6',
    messagingSenderId: '361313252323',
    projectId: 'event-c5221',
    storageBucket: 'event-c5221.firebasestorage.app',
    iosBundleId: 'com.example.eventhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj9_KNHx3GFoV2cekrmX6m4T2RFyWxBC0',
    appId: '1:361313252323:ios:92898f0ef7968aada966d6',
    messagingSenderId: '361313252323',
    projectId: 'event-c5221',
    storageBucket: 'event-c5221.firebasestorage.app',
    iosBundleId: 'com.example.eventhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa3ww_GZH7SabiN1nszzYtmwjEtwcCp0c',
    appId: '1:361313252323:web:d26087dde81bb4bba966d6',
    messagingSenderId: '361313252323',
    projectId: 'event-c5221',
    authDomain: 'event-c5221.firebaseapp.com',
    storageBucket: 'event-c5221.firebasestorage.app',
  );
}
